server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: studentservice
          uri: lb://studentservice
          predicates:
            - Path=/students/**

        - id: applicationservice
          uri: lb://applicationservice
          predicates:
            - Path=/applications/**

        - id: companyservice
          uri: lb://companyservice
          predicates:
            - Path=/companies/**

        - id: opportunityservice
          uri: lb://opportunityservice
          predicates:
            - Path=/opportunities/**

        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/auth/**
