server:
  port: 8082

spring:
  application:
    name: applicationservice

  datasource:
    url: jdbc:mysql://localhost:3306/application_db
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
