server:
  port: 8084

spring:
  application:
    name: companyservice
  datasource:
    url: jdbc:mysql://localhost:3306/company_db
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true